# Generated by Django 4.1.3 on 2022-12-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characters',
            options={'ordering': ['id'], 'verbose_name': 'Персонажи серии Devil May Cry', 'verbose_name_plural': 'Персонажи серии Devil May Cry'},
        ),
    ]
